"""create users table

Revision ID: 07565692251d
Revises: ffdc0a98111c
Create Date: 2024-08-21 19:41:38.847300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07565692251d'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('highlight_img', sa.String(length=250), nullable=True),
    sa.Column('img_1', sa.String(length=250), nullable=True),
    sa.Column('img_2', sa.String(length=250), nullable=True),
    sa.Column('img_3', sa.String(length=250), nullable=True),
    sa.Column('img_4', sa.String(length=250), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surface', sa.String(length=50), nullable=True),
    sa.Column('gas', sa.Integer(), nullable=True),
    sa.Column('resource_access', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('curved_roads', sa.Integer(), nullable=True),
    sa.Column('origin_city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('log_entry', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
